site_name: Charithw's WF Guide Hub
site_url: https://cw-warframe-guides.github.io/
theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: slate
    primary: custom
    accent: custom
  logo: images/Logo.svg
  favicon: images/favicon.png
  font:
    text: Lato
    code: Roboto Mono
  features:
    - navigation.tracking
    - navigation.tabs

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Guide Index: guide_index.md
  - More:
      - Feedback: feedback.md
      - Credits: credits.md

plugins:
  - search
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      width: 100%
      height: auto
      zoomable: true
      draggable: true

markdown_extensions:
  - md_in_html
  - attr_list
  - toc:
      toc_depth: 3
  - pymdownx.snippets:
      base_path: docs/data

extra_javascript:
  - javascripts/glightbox-scroll-zoom.js
  - javascripts/amp.js
  - javascripts/items-cache.js
  - javascripts/prime-list.js
  - javascripts/resurgence.js
  - javascripts/sentinel-images.js
  - javascripts/nav-dropdown.js
  - javascripts/feedback-form.js