site_name: Charithw's WF Guide Hub
theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: slate
    primary: custom
    accent: custom
  font:
    text: Lato
    code: Roboto Mono
  features:
    - navigation.tracking
    - navigation.tabs

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Guide Index: guides/guide_index.md

extra_javascript:
  - https://fonts.googleapis.com/css2?family=Cinzel:wght@600&display=swap